# Модуль NumPy. Случайные числа

> Случайное число — это число, которое возникает в результате случайного процесса.

> Псевдослучайные числа — это такая последовательность чисел, которая возникает с помощью применения математических формул к какому-то исходному числу (например, текущему времени в микросекундах). Элементы, получаемые таким образом, почти не зависят друг от друга: например, при генерации следующего 0 или 1 не имеет значения, что выпало ранее — 0 или 1.

## Случайные числа в NumPy

### Генерация float

In [ ]:
import numpy as np
np.random.rand() # диапазон 0 - 1 (не включительно)

0.8480452668216507

In [ ]:
np.random.rand() * 100 # диапазон 0 - 100 (не включительно)

83.91345799118089

In [ ]:
np.random.rand(5) # в скобке задаётся форма маccива - одномерный

array([0.82669147, 0.80959841, 0.48036491, 0.43507705, 0.04083412])

In [ ]:
np.random.rand(4, 3) # - двумерный

array([[0.57244637, 0.78447217, 0.60782189],
       [0.15901487, 0.65169943, 0.14646185],
       [0.83721766, 0.35347772, 0.89811282],
       [0.40717171, 0.58337894, 0.78339447]])

In [147]:
np.random.rand(2, 3, 4, 10, 12, 23) # - шестимерный

array([[[[[[5.73272909e-01, 9.59856069e-01, 6.51366754e-01, ...,
            4.53097530e-01, 8.18696272e-01, 7.66897066e-01],
           [2.87676285e-01, 7.20537798e-01, 2.50898535e-01, ...,
            9.49986287e-01, 6.26752717e-01, 9.23410999e-01],
           [2.03409832e-01, 7.39560978e-01, 8.70964182e-01, ...,
            1.04281484e-01, 5.46011865e-01, 1.20824800e-01],
           ...,
           [2.77507970e-01, 3.69992796e-02, 7.90249366e-01, ...,
            5.69128450e-01, 2.41820136e-01, 4.11603011e-01],
           [7.26410893e-01, 1.04277105e-01, 7.60257409e-01, ...,
            3.30280883e-01, 3.42931338e-01, 4.73738680e-01],
           [5.93489845e-01, 5.55063582e-01, 3.32506469e-02, ...,
            2.34026293e-01, 1.95086612e-01, 7.80503841e-01]],

          [[8.82399323e-01, 3.17740592e-01, 5.88631039e-01, ...,
            6.30131618e-01, 1.86928440e-01, 4.91803482e-01],
           [2.80447660e-01, 9.38123307e-01, 4.88234064e-01, ...,
            4.74607173e-01, 8.61400

In [ ]:
shape = (2, 3)
np.random.rand(shape) # rand не принимает кортажи

TypeError: 'tuple' object cannot be interpreted as an integer

In [ ]:
shape = (2, 3)
np.random.rand(*shape) # можа расспокавать не это не эстетично

array([[0.37506398, 0.51833375, 0.9429855 ],
       [0.46091605, 0.38537107, 0.57605816]])

In [ ]:
shape = (5, 3)
np.random.sample(shape)

array([[89.42173325, 87.53164604, 10.96946411],
       [89.33114865,  6.8795761 , 61.46682978],
       [60.83334825, 47.72272909, 23.99599048],
       [29.69348094, 35.38439054, 45.99039047],
       [40.49087344, 37.74522849, 86.50003045]])

__uniform(low=0.0, high=1.0, size=None)__
- Первые два аргумента — нижняя и верхняя границы диапазона в формате float, третий опциональный аргумент — форма массива (если не задан, возвращается одно число). Форма массива задаётся кортежем или одним числом.

In [ ]:
np.random.uniform() # 0 - 1     -одно число

0.9601097930060358

In [ ]:
np.random.uniform(5) # 0 - 5    -одно число

4.781101413749404

In [ ]:
np.random.uniform(-10, 30) # -10 - 30   -одно число

26.404077538622857

In [ ]:
np.random.uniform(500, size=()) # 0 - 500, size=None - одно число

array(460.26302783)

In [ ]:
np.random.uniform(-1000, 500, size=())# -1000 - 500, size=None - одно число

array(-150.10619869)

In [ ]:
np.random.uniform(500, size=4) # 0 - 500 size=4 - четырёхмерный

array([209.44042618, 109.73960388, 412.15249777, 165.20937143])

In [ ]:
np.random.uniform(-1000, 500, size=3) # -1000 - 500 size=3 - трёхмерный

array([  80.89190529,  195.31911194, -491.30105582])

In [ ]:
np.random.uniform(size=(2, 3)) # 0 - 1 size=(2, 3) - многомерный 2x3

array([[0.6290601 , 0.39122515, 0.5626407 ],
       [0.28335971, 0.94862165, 0.50006677]])

In [ ]:
np.random.uniform(500, size=(2, 3)) # 0 - 1500 size=(2, 3) - многомерный 2x3

array([[358.37798683, 271.61562616, 316.00805114],
       [147.51717587, 364.45083356, 361.03321672]])

In [ ]:
np.random.uniform(-1000, 500, size=(2, 3)) # -1000 - 500 size=(2, 3) - многомерный 2x3

array([[-506.30057951,  -36.89452061, -920.16094246],
       [-127.66976071, -945.80094702, -866.99924056]])

### Генерация int

randint(low, high=None, size=None, dtype=int)
> Функцию randint нельзя запустить совсем без параметров, необходимо указать хотя бы одно число.

- Если указан только аргумент low, числа будут генерироваться от 0 до low-1, то есть верхняя граница не включается.
- Если задать low и high, числа будут генерироваться от low (включительно) до high (не включительно).
- size задаёт форму массива уже привычным для вас образом: одним числом — для одномерного или кортежем — для многомерного.