# Модуль NumPy. Массивы

МАССИВ — это структура данных, в которой:
1. Элементы хранятся в указанном порядке.
2. Каждый элемент можно получить по индексу за одинаковое время.
3. Все элементы приведены к одному и тому же типу данных.
4. Максимальное число элементов и объём выделенной памяти заданы заранее (программистом и/или компьютером)

__Размерностью массива__ называют то число индексов, которое необходимо для однозначного получения элемента из массива.
- соответственно, чтобы найти элемент в массиве размерности 1 (строка из чисел) достаточно одного индекса.
- В двумерном массиве (таблице из чисел) потребуется уже два индекса: номер строки и номер столбца.
- Для трёхмерного массива (например, контейнеры на судне расположены по длине, ширине и высоте судна) потребуется уже три индекса.
>Максимальная размерность массива программно не ограничена, но с добавлением каждой размерности в несколько раз увеличивается объём требуемой для его хранения памяти. Поэтому в какой-то момент места для массива большой размерности может не хватить, однако фактическая максимальная размерность зависит от возможностей компьютера.

__Форма (структура) массива__ — это информация о количестве размерностей массива и протяжённости массива по каждой из размерностей. Например, можно задать двумерный массив размера 3x5 — у этой таблицы две размерности: 3 строки и 5 столбцов.

## Массивы в Numpy

### 1. Создание массива из списка

In [ ]:
import numpy as np
arr = np.array([1,5,2,9,10])
arr 

array([ 1,  5,  2,  9, 10])

In [ ]:
print(arr) # пример вывода без print (выше) и с print

[ 1  5  2  9 10]


In [ ]:
print(type(arr))
# Название ndarray — это сокращение от n-dimensional array, n-мерный массив.

<class 'numpy.ndarray'>


In [9]:
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ])
nd_arr

array([[12, 45, 78],
       [34, 56, 13],
       [12, 98, 76]])

In [ ]:
print(nd_arr) # пример вывода без print (выше) и с print

[[12 45 78]
 [34 56 13]
 [12 98 76]]


## 2. Типы данных в массиве

In [ ]:
arr = np.array([1,5,2,9,10])
arr.dtype
# NumPy автоматически определил наш набор чисел как числа типа int64.

dtype('int64')

In [25]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr

array([ 1,  5,  2,  9, 10], dtype=int8)

In [23]:
print(arr) # пример вывода без print (выше) и с print

[ 1  5  2  9 10]


In [ ]:
arr[2] = 2000 % -128 # -128 - это мин знач для np.int8
arr

array([  1,   5, -48,   9,  10], dtype=int8)

In [29]:
arr[2] = 125.5
arr

array([  1,   5, 125,   9,  10], dtype=int8)

In [ ]:
# Строку, которую можно преобразовать в число, можно сразу положить в массив. Она будет приведена к нужному типу автоматически:
arr[2] = '12'
arr

array([ 1,  5, 12,  9, 10], dtype=int8)

In [31]:
arr[2] = 'test'
arr

ValueError: invalid literal for int() with base 10: 'test'

In [33]:
arr = np.float64(arr)
arr

array([ 1.,  5., 12.,  9., 10.])

>>При преобразовании типов данных в массиве не забывайте о том, что часть чисел может потерять смысл, если менять тип данных с более ёмкого на менее ёмкий:

In [ ]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr

array([12321, -1234,  3435,  -214,   100], dtype=int32)

In [37]:
arr = np.uint8(arr)
arr

array([ 33,  46, 107,  42, 100], dtype=uint8)

## 3. Свойства NumPy-массивов

In [58]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

1. Размерность массива

In [59]:
arr.ndim
# одномерный 

1

In [60]:
nd_arr.ndim
# двумерный

2

2. Общее число (кол-во) элементолв в массиве

In [61]:
arr.size

5

In [62]:
nd_arr.size

9

3. Форма или структура массива

In [63]:
arr.shape

(5,)

In [64]:
nd_arr.shape

(3, 3)

4. Размер ("вес") каждого элемента в массиве (сколько байт)

In [65]:
arr.itemsize

1

In [66]:
nd_arr.itemsize

2

## 4. Заполнение новых массивов

→ Не всегда значения, которые будут храниться в массиве, уже доступны, а иметь для них массив уже хочется.

- нулевой массив

In [85]:
zeros_1d = np.zeros(5)
zeros_1d

array([0., 0., 0., 0., 0.])

In [86]:
zeros_2d = np.zeros((5, 3), dtype=np.int8)
zeros_2d

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int8)

In [87]:
zeros_3d = np.zeros((5, 4, 3), dtype=np.float32)
zeros_3d.shape

(5, 4, 3)

In [88]:
zeros_3d = np.zeros((5, 4, 3), dtype=np.float32)
zeros_3d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

- удобные функции для создания одномерных массивов

>в отличие от __range__, в функции __arange__ все параметры могут быть float 

In [89]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [90]:
np.arange(2.5, 5)

array([2.5, 3.5, 4.5])

In [91]:
np.arange(2.5, 5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5])

In [92]:
np.arange(2.5, 5.5, 0.5)

array([2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [93]:
np.arange(2.5, 5, 0.5, dtype=np.float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

>> Операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Поэтому в __arange__  не рекомендуется использовать float

Для работы с дробными параметрами start, stop и step лучше использовать функцию ___linspace___ (англ. linear space — линейное пространство). Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

__np.linspace (start, stop, num=50, endpoint=True, retstep=False, dtype=None)__

- start и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
- num — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
- endpoint — включён или исключён конец диапазона (по умолчанию включён);
- retstep (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
- dtype — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).
